// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"github.com/zeromicro/go-zero/rest/httpx"
	"net/http"

	"iot-platform/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/device/list",
				Handler: DeviceListHandler(serverCtx),
			},
			{
				Method: http.MethodPost,
				Path:   "/hello",
				Handler: func(w http.ResponseWriter, r *http.Request) {
					httpx.OkJsonCtx(r.Context(), w, map[string]string{"status": "ok"})
				},
			},
		},
	)
}
