// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"iot-platform/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/device/list",
				Handler: DeviceListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/list",
				Handler: ProductListHandler(serverCtx),
			},
		},
	)
}
