// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type BasicRequest struct {
	Page int    `json:"page,optional"`
	Size int    `json:"size,optional"`
	Name string `json:"name,optional"`
}

type DeviceCreateRequest struct {
	Name            string `json:"name"`
	ProductIdentity string `json:"product_identity"`
}

type DeviceCreateResponse struct {
}

type DeviceDeleteRequest struct {
	Identity string `json:"identity"`
}

type DeviceDeleteResponse struct {
}

type DeviceLisBasic struct {
	Identity    string `json:"identity"`
	ProductName string `json:"product_name"`
	Name        string `json:"name"`
	Key         string `json:"key"`
	Secret      string `json:"secret"`
}

type DeviceListRequest struct {
	BasicRequest
}

type DeviceListResponse struct {
	List  []*DeviceLisBasic `json:"list"`
	Count int64             `json:"count"`
}

type DeviceModifyRequest struct {
	Identity string `json:"identity"`
	DeviceCreateRequest
}

type DeviceModifyResponse struct {
}

type ProductCreateRequest struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type ProductCreateResponse struct {
}

type ProductDeleteRequest struct {
	Identity string `json:"identity"`
}

type ProductDeleteResponse struct {
}

type ProductLisBasic struct {
	Identity  string `json:"identity"`
	Name      string `json:"name"`
	Key       string `json:"key"`
	Desc      string `json:"desc"`
	CreatedAt string `json:"created_at"`
}

type ProductListRequest struct {
	BasicRequest
}

type ProductListResponse struct {
	List  []*ProductLisBasic `json:"list"`
	Count int64              `json:"count"`
}

type ProductModifyRequest struct {
	Identity string `json:"identity"`
	ProductCreateRequest
}

type ProductModifyResponse struct {
}
