// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type DeviceLisBasic struct {
	Identity    string `json:"identity"`
	ProductName string `json:"product_name"`
	Name        string `json:"name"`
	Key         string `json:"key"`
	Secret      string `json:"secret"`
}

type DeviceListRequest struct {
	Page int    `json:"page,optional"`
	Size int    `json:"size,optional"`
	Name string `json:"name,optional"`
}

type DeviceListResponse struct {
	List  []*DeviceLisBasic `json:"list"`
	Count int64             `json:"count"`
}
