// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type UserLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginResponse struct {
	Token string `json:"token"`
}
