// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.20.3
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthReq) Reset() {
	*x = UserAuthReq{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthReq) ProtoMessage() {}

func (x *UserAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthReq.ProtoReflect.Descriptor instead.
func (*UserAuthReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserAuthReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserAuthRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Extend        map[string]string      `protobuf:"bytes,3,rep,name=extend,proto3" json:"extend,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthRsp) Reset() {
	*x = UserAuthRsp{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthRsp) ProtoMessage() {}

func (x *UserAuthRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthRsp.ProtoReflect.Descriptor instead.
func (*UserAuthRsp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserAuthRsp) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *UserAuthRsp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserAuthRsp) GetExtend() map[string]string {
	if x != nil {
		return x.Extend
	}
	return nil
}

type OpenAuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAuthReq) Reset() {
	*x = OpenAuthReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAuthReq) ProtoMessage() {}

func (x *OpenAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAuthReq.ProtoReflect.Descriptor instead.
func (*OpenAuthReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *OpenAuthReq) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type OpenAuthRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAuthRsp) Reset() {
	*x = OpenAuthRsp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAuthRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAuthRsp) ProtoMessage() {}

func (x *OpenAuthRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAuthRsp.ProtoReflect.Descriptor instead.
func (*OpenAuthRsp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\btemplate\"#\n" +
	"\vUserAuthReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xaf\x01\n" +
	"\vUserAuthRsp\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x129\n" +
	"\x06extend\x18\x03 \x03(\v2!.template.UserAuthRsp.ExtendEntryR\x06extend\x1a9\n" +
	"\vExtendEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\vOpenAuthReq\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\"\r\n" +
	"\vOpenAuthRsp2v\n" +
	"\x04User\x124\n" +
	"\x04Auth\x12\x15.template.UserAuthReq\x1a\x15.template.UserAuthRsp\x128\n" +
	"\bOpenAuth\x12\x15.template.OpenAuthReq\x1a\x15.template.OpenAuthRspB\bZ\x06./userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_proto_goTypes = []any{
	(*UserAuthReq)(nil), // 0: template.UserAuthReq
	(*UserAuthRsp)(nil), // 1: template.UserAuthRsp
	(*OpenAuthReq)(nil), // 2: template.OpenAuthReq
	(*OpenAuthRsp)(nil), // 3: template.OpenAuthRsp
	nil,                 // 4: template.UserAuthRsp.ExtendEntry
}
var file_user_proto_depIdxs = []int32{
	4, // 0: template.UserAuthRsp.extend:type_name -> template.UserAuthRsp.ExtendEntry
	0, // 1: template.User.Auth:input_type -> template.UserAuthReq
	2, // 2: template.User.OpenAuth:input_type -> template.OpenAuthReq
	1, // 3: template.User.Auth:output_type -> template.UserAuthRsp
	3, // 4: template.User.OpenAuth:output_type -> template.OpenAuthRsp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
