// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package user_client

import (
	"context"

	"iot-platform/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserAuthReq = user.UserAuthReq
	UserAuthRsp = user.UserAuthRsp

	User interface {
		Auth(ctx context.Context, in *UserAuthReq, opts ...grpc.CallOption) (*UserAuthRsp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Auth(ctx context.Context, in *UserAuthReq, opts ...grpc.CallOption) (*UserAuthRsp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Auth(ctx, in, opts...)
}
