// Code generated by goctl. DO NOT EDIT!
// Source: device.proto

package device

import (
	"context"
	"iot-platform/device/types/device"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendMessageReq  = device.SendMessageReq
	SendMessageResp = device.SendMessageResp

	Device interface {
		SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	}

	defaultDevice struct {
		cli zrpc.Client
	}
)

func NewDevice(cli zrpc.Client) Device {
	return &defaultDevice{
		cli: cli,
	}
}

func (m *defaultDevice) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := device.NewDeviceClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}
