// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type SendMessageRequest struct {
	ProductKey string `json:"product_key"`
	DeviceKey  string `json:"device_key"`
	Data       string `json:"data"`
}

type SendMessageResponse struct {
	Message string `json:"message"`
}
